const CategoryPropertyData = [
  {
    category: "shop",
    sellername: "SELLER NAME",
    state: "Assam",
    district: "Guwagati Road",
    village: "Silapatha",
    tscode: "872626",
    price: "20,00000",
    area: "0.00008",
    measles: "1234",
    description: "Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.",
  },
  {
    category: "flat",
    sellername: "SELLER NAME",
    state: "Assam",
    district: "Guwagati Road",
    village: "Silapatha",
    tscode: "872685",
    price: "10,000",
    area: "0.00008",
    measles: "1234",
    description: "Lorem, ipsum dolor sit amere corporis quaerat! amere corporis quaerat! Ipsum.",
  },
  {
    category: "builing",
    sellername: "SELLER NAME",
    state: "Assam",
    district: "Guwagati Road",
    village: "Silapatha",
    tscode: "872685",
    price: "10,000",
    area: "0.00008",
    measles: "1234",
    description: "Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.Lorem, ipsum dolor sit amere corporis quaerat! Ipsum.",
  },
];

export default CategoryPropertyData;